version: 0.2

env:
  variables:
    REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID: '${REPLACE_AWS_COGNITO_IDENTITY_POOL_ID}'
    REACT_APP_AWS_REGION: '${REPLACE_AWS_REGION}'
    REACT_APP_AWS_USER_POOLS_ID: '${REPLACE_AWS_USER_POOLS_ID}'
    REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID: '${REPLACE_AWS_USER_POOLS_WEB_CLIENT_ID}'
    REACT_APP_DOMAIN: '${REPLACE_DOMAIN}'
    REACT_APP_REDIRECT_SIGN_IN: '${REPLACE_REDIRECT_SIGN_IN}'
    REACT_APP_REDIRECT_SIGN_OUT: '${REPLACE_REDIRECT_SIGN_OUT}'
    REACT_APP_ORCID_CLIENT_ID: '${REPLACE_ORCID_CLIENT_ID}'
    REACT_APP_ORCID_CLIENT_SECRET: '${REPLACE_ORCID_CLIENT_SECRET}'
    REACT_APP_ORCID_REDIRECT_URI: '${REPLACE_ORCID_REDIRECT_URI}'
    REACT_APP_ORCID_BASE_URL: '${REPLACE_ORCID_BASE_URL}'
    REACT_APP_ALMA_API_URL: '${REPLACE_ALMA_API_URL}'
    REACT_APP_API_URL: '${REPLACE_API_URL}'

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - env
      - npm install
      - pip3 install aws-sam-cli
      - apt install -q -y jq

  build:
    commands:
      - npm run build
  post_build:
    commands:
      - sam package --template-file ./templates/sar_application_template.yml --s3-bucket $S3_BUCKET --output-template-file sampackaged_raw.yaml
      # Setting a timestamp for the build in labels
      - BUILD_TIMESTAMP=$(date -Iseconds)
      # Getting latest version tag from git
      - APPLICATION_VERSION=$(curl -s  https://api.github.com/repos/BIBSYSDEV/$GIT_REPO/releases/latest | jq -r '.tag_name')
      # Updating metadata.labels in template
      - envsubst '${CODEBUILD_RESOLVED_SOURCE_VERSION},${GIT_REPO},${BUILD_TIMESTAMP}' < sampackaged_raw.yaml > sampackaged.yaml
      # publishing to SAR
      - sam publish  --semantic-version $APPLICATION_VERSION  --template sampackaged.yaml
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
