version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: test1
      buildspec: buildspec.testrun.yml
      env:
        variables:
          BUILD_ID: test1
    - identifier: test2
      buildspec: buildspec.testrun.yml
      env:
        variables:
          BUILD_ID: test2

