version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - build/*
    - discard-paths: yes
  secondary-artifacts:
    static:
      files:
        - build/static/*
      base-directory: static
  