version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - echo --------------------------------------
      - echo $REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID
      - echo $REACT_APP_AWS_USER_POOLS_ID
      - echo $REACT_APP_REDIRECT_SIGN_OUT
      - echo $REACT_APP_REDIRECT_SIGN_IN
      - echo --------------------------------------
      - env
      - npm run build
      - echo --------------------------------------
      - echo $REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID
      - echo $REACT_APP_AWS_USER_POOLS_ID
      - echo $REACT_APP_REDIRECT_SIGN_OUT
      - echo $REACT_APP_REDIRECT_SIGN_IN
      - echo --------------------------------------
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
