version: 0.2

env:
  parameter-store:
    REACT_APP_AWS_USER_POOLS_ID: CognitoUserPoolId # from nva-identity-service
    REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID: CognitoUserPoolAppClientId # from nva-identity-service
    REACT_APP_DOMAIN: CognitoAuthenticationDomain # from nva-identity-service
    REACT_APP_REDIRECT_SIGN_IN: CognitoFrontendApplicationUrl # from nva-identity-service
    REACT_APP_REDIRECT_SIGN_OUT: CognitoFrontendApplicationLogoutUrl # from nva-identity-service
    REACT_APP_ORCID_BASE_URL: OrcidBaseUrl
    REACT_APP_API_HOST: /NVA/ApiDomain
    REACT_APP_APP_HOST: /NVA/ApplicationDomain
    CYPRESS_RECORD_KEY: CypressRecordKey

  secrets-manager:
    REACT_APP_ORCID_CLIENT_ID: OrcidClientID
    #  Values to be assigned outside of pipeline
    # REACT_APP_AWS_REGION
    # REACT_APP_USE_MOCK

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - env
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
