version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo $REACT_APP_REDIRECT_SIGN_IN
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
