version: 0.2

env:
  variables:

    REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID: '${REPLACE_AWS_COGNITO_IDENTITY_POOL_ID}'
    REACT_APP_AWS_REGION: '${REPLACE_REACT_APP_AWS_REGION}'
    REACT_APP_AWS_USER_POOLS_ID: '${REPLACE_AWS_USER_POOLS_ID}'
    REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID: '${REPLACE_AWS_USER_POOLS_WEB_CLIENT_ID}'
    REACT_APP_DOMAIN: '${REPLACE_DOMAIN}'
    REACT_APP_REDIRECT_SIGN_IN: '${REPLACE_REDIRECT_SIGN_IN}'
    REACT_APP_REDIRECT_SIGN_OUT: '${REPLACE_REDIRECT_SIGN_OUT}'
    REACT_APP_ORCID_CLIENT_ID: '${REPLACE_ORCID_CLIENT_ID}'
    REACT_APP_ORCID_CLIENT_SECRET: '${REPLACE_ORCID_CLIENT_SECRET}'
    REACT_APP_ORCID_REDIRECT_URI: '${REPLACE_ORCID_REDIRECT_URI}'
    REACT_APP_ORCID_BASE_URL: '${REPLACE_ORCID_BASE_URL}'
    REACT_APP_PUBLICATION_CHANNEL_API_URL: '${REPLACE_PUBLICATION_CHANNEL_API_URL}'
    REACT_APP_AUTHORITY_REGISTER_API_URL: '${REPLACE_AUTHORITY_REGISTER_API_URL}'
    REACT_APP_ALMA_API_URL: '${REPLACE_ALMA_API_URL}'
    REACT_APP_API_URL: '${REPLACE_API_URL}'

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - env
      - npm install
      - pip3 install aws-sam-cli
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - sam package --debug --template-file ./templates/sar_application_template.yml --s3-bucket $S3_BUCKET --output-template-file sampackaged.yaml
      - sam publish --template sampackaged.yaml

artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
