version: 0.2

env:
  parameter-store:
    REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID: REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID
    REACT_APP_AWS_USER_POOLS_ID: REACT_APP_AWS_USER_POOLS_ID
    REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID: REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID
    REACT_APP_DOMAIN: REACT_APP_DOMAIN
    REACT_APP_REDIRECT_SIGN_IN: REACT_APP_REDIRECT_SIGN_IN
    REACT_APP_REDIRECT_SIGN_OUT: REACT_APP_REDIRECT_SIGN_OUT
    REACT_APP_ORCID_CLIENT_ID: REACT_APP_ORCID_CLIENT_ID
    REACT_APP_ORCID_REDIRECT_URI: REACT_APP_ORCID_REDIRECT_URI
    REACT_APP_ORCID_BASE_URL: REACT_APP_ORCID_BASE_URL
    REACT_APP_API_URL: REACT_APP_API_URL
    REACT_APP_ALMA_API_URL: REACT_APP_ALMA_API_URL
  secrets-manager:
    REACT_APP_ORCID_CLIENT_SECRET: REACT_APP_ORCID_CLIENT_SECRET
    #  Values to be assigned outside of pipeline
    # REACT_APP_AWS_REGION
    # REACT_APP_USE_MOCK

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - env
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
