version: 0.2

env:
  variables:
    REACT_APP_AWS_REGION: raill-raill
  parameter-store:
    REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID: REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID
    REACT_APP_AWS_USER_POOLS_ID: REACT_APP_AWS_USER_POOLS_ID
    REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID: REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID
    REACT_APP_DOMAIN: REACT_APP_DOMAIN
    REACT_APP_REDIRECT_SIGN_IN: REACT_APP_REDIRECT_SIGN_IN
    REACT_APP_REDIRECT_SIGN_OUT: REACT_APP_REDIRECT_SIGN_OUT

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - env
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
