AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  NvaFrontendBucketName:
    Description: Name of S3 bucket for frontend
    Type: String
Resources:
  NvaFrontendBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: 
        !Ref NvaFrontendBucketName
      PolicyDocument: 
        Statement: 
          Action: 
            - 's3:GetObject'
            - 's3:putObject'
          Effect: 'Allow'
          Resource: 
            !Sub 'arn:aws:s3:::${NvaFrontendBucketName}/*'
          Principal: 
#            AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}'
            Service:
              cloudformation.amazonaws.com
              cloudfront.amazonaws.com
  CloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: !Sub '${NvaFrontendBucketName}-access-identity'
  NvaFrontendBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref NvaFrontendBucketName
  NvaCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub '${NvaFrontendBucketName}.s3.amazonaws.com'
          Id: !Sub 'S3-${NvaFrontendBucketName}'
          S3OriginConfig:
            OriginAccessIdentity:  !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        Enabled: true
        Comment: NVA frontend distribution
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: 
            !Sub 'S3-${NvaFrontendBucketName}'
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: '/index.html'
        PriceClass: PriceClass_100
        Restrictions:
          GeoRestriction:
            RestrictionType:
              none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
        - ErrorCode: 404
          ErrorCachingMinTTL: 10
          ResponseCode: 200
          ResponsePagePath: '/index.html'
        - ErrorCode: 403
          ErrorCachingMinTTL: 10
          ResponseCode: 200
          ResponsePagePath: '/index.html'
