version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - env
      - npm ci
  build:
    commands:
      - VERSION=v$(date +%Y%m%d)
      - BUILDS_BUCKET=frontend-builds-$(aws sts get-caller-identity --query Account --output text)
      - TO=s3://$BUILDS_BUCKET/builds/$VERSION
      - npm run deploy_sandbox
      - aws s3 mv ./build ${TO}/sandbox --recursive
      # - npm run deploy_prod
      # - aws s3 mv ./build ${TO}/prod --recursive
      # - npm run deploy_test
      # - aws s3 mv ./build ${TO}/test --recursive
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
