version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - env
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend
