version: 0.2

batch:
  fast-fail: true
  build-list:
    - identifier: prod-build
      buildspec: buildspecs/production_build.yml
    - identifier: cypress-tests
      buildspec: buildspecs/cypress_tests.yml
