# buildspec file for the NVA-frontend-github-check build in AWS (dev). Used to run tests with mock data for PRs in GitHub.

version: 0.2

env:
  variables:
    REACT_APP_API_HOST: 'https://my-nva-api.no'
    REACT_APP_USE_MOCK: 'true'
  secrets-manager:
    CYPRESS_RECORD_KEY: CypressRecordKey

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci
  build:
    commands:
      - npm run test:cypress
