# buildspec file for the NVA-frontend-github-check build in AWS (dev). Used to run tests with mock data for PRs in GitHub.

version: 0.2

env:
  variables:
    VITE_API_HOST: 'https://my-nva-api.no'
    VITE_USE_MOCK: 'true'

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies
      - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib xdg-utils
      - npm ci
  build:
    commands:
      - npm run test:cypress
