# buildspec file for the NVA-frontend-github-check build in AWS (dev). Used to run tests with mock data for PRs in GitHub.

version: 0.2

env:
  image: public.ecr.aws/cypress-io/cypress/browsers:node-20.17.0-chrome-128.0.6613.137-1-ff-130.0.1-edge-128.0.2739.67-1
  variables:
    VITE_API_HOST: 'https://my-nva-api.no'
    VITE_USE_MOCK: 'true'

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci
  build:
    commands:
      - npm run test:cypress
