version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib # https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies
      - npm ci
  build:
    commands:
      - npm run build
