version: 0.2

env:
  image: public.ecr.aws/docker/library/node:slim
  variables:
    VITE_API_HOST: 'https://my-nva-api.no'

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci
  build:
    commands:
      - npm run build
