import { VocabularyData } from '../../types/vocabulary.types';

//https://github.com/brinxmat/hrcs-skos/blob/main/src/hrcs_category.json
export const hrcsCategories: VocabularyData = {
  categories: [
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_01blo',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_01BLO',
      cristinIdentifier: '1',
      label: {
        en: 'Blood',
        nb: 'Blod',
      },
      name: 'Blood',
      shortName: 'Blood',
      related: 'https://purl.bioontology.org/ontology/ICD10/D50-D89.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_10men',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_10MEN',
      cristinIdentifier: '2',
      label: {
        en: 'Mental Health',
        nb: 'Mental helse',
      },
      name: 'Mental health',
      shortName: 'Mental',
      related: 'https://purl.bioontology.org/ontology/ICD10/F00-F99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_11met',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_11MET',
      cristinIdentifier: '3',
      label: {
        en: 'Metabolic and Endocrine',
        nb: 'Stoffskifte og hormoner',
      },
      name: 'Metabolic and endocrine',
      shortName: 'Metabolic',
      related: 'https://purl.bioontology.org/ontology/ICD10/E00-E90.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_12mus',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_12MUS',
      cristinIdentifier: '4',
      label: {
        en: 'Musculoskeletal',
        nb: 'Muskulatur og skjelett',
      },
      name: 'Musculoskeletal',
      shortName: 'Muscle',
      related: 'https://purl.bioontology.org/ontology/ICD10/M00-M99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_13neu',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_13NEU',
      cristinIdentifier: '5',
      label: {
        en: 'Neurological',
        nb: 'Nevrologisk',
      },
      name: 'Neurological',
      shortName: 'Neuro',
      related: 'https://purl.bioontology.org/ontology/ICD10/G00-G99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_14ora',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_14ORA',
      cristinIdentifier: '6',
      label: {
        en: 'Oral and Gastrointestinal',
        nb: 'Munnhule, mage-tarm',
      },
      name: 'Oral and gastrointestinal',
      shortName: 'Oral',
      related: 'https://purl.bioontology.org/ontology/ICD10/K00-K93.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_15ren',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_15REN',
      cristinIdentifier: '7',
      label: {
        en: 'Renal and Urogenital',
        nb: 'Nyrer, urinveier og kjønnsorgan',
      },
      name: 'Renal and urogenital',
      shortName: 'Renal',
      related: 'https://purl.bioontology.org/ontology/ICD10/N00-N99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_16rep',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_16REP',
      cristinIdentifier: '8',
      label: {
        en: 'Reproductive Health and Childbirth',
        nb: 'Forplantning og fødsel',
      },
      name: 'Reproductive health and childbirth',
      shortName: 'Reproduction',
      related: [
        'https://purl.bioontology.org/ontology/ICD10/O00-O99.9',
        'https://purl.bioontology.org/ontology/ICD10/P00-P96.9',
      ],
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_17res',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_17RES',
      cristinIdentifier: '9',
      label: {
        en: 'Respiratory',
        nb: 'Lunger og luftveier',
      },
      name: 'Respiratory',
      shortName: 'Respiratory',
      related: 'https://purl.bioontology.org/ontology/ICD10/J00-J99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_18ski',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_18SKI',
      cristinIdentifier: '10',
      label: {
        en: 'Skin',
        nb: 'Hud',
      },
      name: 'Skin',
      shortName: 'Skin',
      related: 'https://purl.bioontology.org/ontology/ICD10/L00-L99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_19str',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_19STR',
      cristinIdentifier: '11',
      label: {
        en: 'Stroke',
        nb: 'Hjerneslag',
      },
      name: 'Stroke',
      shortName: 'Stroke',
      related: 'https://purl.bioontology.org/ontology/ICD10/I00-I99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_02can',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_02CAN',
      cristinIdentifier: '12',
      label: {
        en: 'Cancer and neoplasms',
        nb: 'Kreft',
      },
      name: 'Cancer',
      shortName: 'Cancer',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_20gen',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_20GEN',
      cristinIdentifier: '13',
      label: {
        en: 'Generic Health Relevance',
        nb: 'Generell helserelevans',
      },
      name: 'Generic health relevance',
      shortName: 'Generic',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_21oth',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_21OTH',
      cristinIdentifier: '14',
      label: {
        en: 'Other',
        nb: 'Andre',
      },
      name: 'Disputed aetiology and other',
      shortName: 'Other',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_03car',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_03CAR',
      cristinIdentifier: '15',
      label: {
        en: 'Cardiovascular',
        nb: 'Hjerte og kar',
      },
      name: 'Caridovascular',
      shortName: 'Cardio',
      related: 'https://purl.bioontology.org/ontology/ICD10/I00-I99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_04con',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_04CON',
      cristinIdentifier: '16',
      label: {
        en: 'Congenital Disorders',
        nb: 'Medfødte lidelser',
      },
      name: 'Congenital',
      shortName: 'Congenital',
      related: 'https://purl.bioontology.org/ontology/ICD10/Q00-Q99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_05ear',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_05EAR',
      cristinIdentifier: '17',
      label: {
        en: 'Ear',
        nb: 'Øre',
      },
      name: 'Ear',
      shortName: 'Ear',
      related: 'https://purl.bioontology.org/ontology/ICD10/H60-H95.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_06eye',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_06EYE',
      cristinIdentifier: '18',
      label: {
        en: 'Eye',
        nb: 'Øye',
      },
      name: 'Eye',
      shortName: 'Eye',
      related: 'https://purl.bioontology.org/ontology/ICD10/H00-H59.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_07inf',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_07INF',
      cristinIdentifier: '19',
      label: {
        en: 'Infection',
        nb: 'Infeksjon',
      },
      name: 'Infection',
      shortName: 'Infection',
      related: 'https://purl.bioontology.org/ontology/ICD10/A00-B99.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_08imm',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_08IMM',
      cristinIdentifier: '20',
      label: {
        en: 'Inflammatory and Immune System',
        nb: 'Betennelse og immunsystem',
      },
      name: 'Inflammatory and immune system',
      shortName: 'Immune',
      related: 'https://purl.bioontology.org/ontology/ICD10/D50-D89.9',
    },
    {
      id: 'https://nva.unit.no/hrcs/category/hrcs_hc_09inj',
      type: 'HrcsConcept',
      identifier: 'HRCS_HC_09INJ',
      cristinIdentifier: '21',
      label: {
        en: 'Injuries and Accidents',
        nb: 'Skader og ulykker',
      },
      name: 'Injuries and accidents',
      shortName: 'Injuries',
      related: [
        'https://purl.bioontology.org/ontology/ICD10/S00-T98.9',
        'https://purl.bioontology.org/ontology/ICD10/V01-Y98.9',
      ],
    },
  ],
};
