export { default as ccByImage } from './cc-by.svg';
export { default as ccBySaImage } from './cc-by-sa.svg';
export { default as ccByNdImage } from './cc-by-nd.svg';
export { default as ccByNcImage } from './cc-by-nc.svg';
export { default as ccByNcSaImage } from './cc-by-nc-sa.svg';
export { default as ccByNcNdImage } from './cc-by-nc-nd.svg';
export { default as cc0Image } from './cc0.svg';
export { default as ccImage } from './cc.svg';
export { default as openAccessLogo } from './open-access-logo.svg';
export { default as lockImage } from './lock.svg';

// button images - used by license selector
export { default as ccByButton } from './button-cc-by.svg';
export { default as ccBySaButton } from './button-cc-by-sa.svg';
export { default as ccByNdButton } from './button-cc-by-nd.svg';
export { default as ccByNcButton } from './button-cc-by-nc.svg';
export { default as ccByNcSaButton } from './button-cc-by-nc-sa.svg';
export { default as ccByNcNdButton } from './button-cc-by-nc-nd.svg';
export { default as cc0Button } from './button-cc0.svg';
export { default as ccButton } from './button-cc.svg';
export { default as lockButton } from './button-lock.svg';
