import { describe, expect, it } from 'vitest';
import { AdditionalIdentifier, Registration } from '../../../types/registration.types';
import { getCristinIdentifier, getHandles, getScopusIdentifiers, splitHandles } from './identifier-helpers';

const buildRegistration = (handle?: string, additionalIdentifiers?: AdditionalIdentifier[]): Registration =>
  ({ handle, additionalIdentifiers }) as unknown as Registration;

const handleIdentifier = (value: string): AdditionalIdentifier => ({
  type: 'HandleIdentifier',
  sourceName: 'handle',
  value,
});

describe('getHandles', () => {
  it('Returns an empty list when the registration has no handles', () => {
    expect(getHandles(buildRegistration())).toEqual([]);
  });

  it('Returns the handle from registration.handle', () => {
    expect(getHandles(buildRegistration('https://hdl.handle.net/11250/1'))).toEqual(['https://hdl.handle.net/11250/1']);
  });

  it('Returns handles identified by type', () => {
    const registration = buildRegistration(undefined, [handleIdentifier('https://hdl.handle.net/11250/1')]);
    expect(getHandles(registration)).toEqual(['https://hdl.handle.net/11250/1']);
  });

  it('Returns handles identified by sourceName alone', () => {
    const registration = buildRegistration(undefined, [
      { type: 'CristinIdentifier', sourceName: 'handle', value: 'https://hdl.handle.net/11250/1' },
    ]);
    expect(getHandles(registration)).toEqual(['https://hdl.handle.net/11250/1']);
  });

  it('Lists registration.handle before the additional handles', () => {
    const registration = buildRegistration('https://hdl.handle.net/10037/2', [
      handleIdentifier('https://hdl.handle.net/11250/1'),
    ]);
    expect(getHandles(registration)).toEqual(['https://hdl.handle.net/10037/2', 'https://hdl.handle.net/11250/1']);
  });

  it('Deduplicates a handle present both on the registration and in additionalIdentifiers', () => {
    const registration = buildRegistration('https://hdl.handle.net/11250/1', [
      handleIdentifier('https://hdl.handle.net/11250/1'),
    ]);
    expect(getHandles(registration)).toEqual(['https://hdl.handle.net/11250/1']);
  });

  it('Ignores identifiers that are not handles', () => {
    const registration = buildRegistration(undefined, [
      { type: 'ScopusIdentifier', sourceName: 'Scopus', value: '2-s2.0-85128230507' },
    ]);
    expect(getHandles(registration)).toEqual([]);
  });
});

describe('splitHandles', () => {
  it('Returns empty lists when there are no handles', () => {
    expect(splitHandles([])).toEqual({ primaryHandles: [], otherHandles: [] });
  });

  it('Shows the only handle even when it is not from an institutional archive', () => {
    expect(splitHandles(['https://hdl.handle.net/10037/2'])).toEqual({
      primaryHandles: ['https://hdl.handle.net/10037/2'],
      otherHandles: [],
    });
  });

  it('Prefers the institutional archive handle over earlier handles', () => {
    const handles = [
      'https://hdl.handle.net/10037/2',
      'https://hdl.handle.net/2447/3',
      'https://hdl.handle.net/11250/1',
    ];
    expect(splitHandles(handles)).toEqual({
      primaryHandles: ['https://hdl.handle.net/11250/1'],
      otherHandles: ['https://hdl.handle.net/10037/2', 'https://hdl.handle.net/2447/3'],
    });
  });

  it('Falls back to the first handle when none are from an institutional archive', () => {
    const handles = ['https://hdl.handle.net/10037/2', 'https://hdl.handle.net/2447/3'];
    expect(splitHandles(handles)).toEqual({
      primaryHandles: ['https://hdl.handle.net/10037/2'],
      otherHandles: ['https://hdl.handle.net/2447/3'],
    });
  });

  it('Shows the first institutional archive handle when there are several', () => {
    const handles = ['https://hdl.handle.net/11250/1', 'https://hdl.handle.net/11250/2'];
    expect(splitHandles(handles)).toEqual({
      primaryHandles: ['https://hdl.handle.net/11250/1'],
      otherHandles: ['https://hdl.handle.net/11250/2'],
    });
  });

  it('Ignores handles where the prefix only appears in the suffix', () => {
    const handles = ['https://hdl.handle.net/10852/112507', 'https://hdl.handle.net/11250/3'];
    expect(splitHandles(handles)).toEqual({
      primaryHandles: ['https://hdl.handle.net/11250/3'],
      otherHandles: ['https://hdl.handle.net/10852/112507'],
    });
  });

  it('Matches an institutional archive handle stored without the resolver URL', () => {
    expect(splitHandles(['https://hdl.handle.net/10037/2', '11250/3'])).toEqual({
      primaryHandles: ['11250/3'],
      otherHandles: ['https://hdl.handle.net/10037/2'],
    });
  });
});

describe('getCristinIdentifier', () => {
  it('Returns undefined when there are no identifiers', () => {
    expect(getCristinIdentifier(buildRegistration())).toBeUndefined();
  });

  it('Omits synthetic identifiers generated by NVA', () => {
    const registration = buildRegistration(undefined, [
      { type: 'CristinIdentifier', sourceName: 'Cristin', value: '10000000' },
    ]);
    expect(getCristinIdentifier(registration)).toBeUndefined();
  });

  it('Prefers an identifier from Cristin over one from another source', () => {
    const registration = buildRegistration(undefined, [
      { type: 'CristinIdentifier', sourceName: 'Scopus', value: '111' },
      { type: 'CristinIdentifier', sourceName: 'Cristin', value: '222' },
    ]);
    expect(getCristinIdentifier(registration)).toBe('222');
  });
});

describe('getScopusIdentifiers', () => {
  it('Returns an empty list when there are no identifiers', () => {
    expect(getScopusIdentifiers(buildRegistration())).toEqual([]);
  });

  it('Returns every Scopus identifier', () => {
    const registration = buildRegistration(undefined, [
      { type: 'ScopusIdentifier', sourceName: 'Scopus', value: '2-s2.0-1' },
      handleIdentifier('https://hdl.handle.net/11250/1'),
      { type: 'ScopusIdentifier', sourceName: 'Scopus', value: '2-s2.0-2' },
    ]);
    expect(getScopusIdentifiers(registration)).toEqual(['2-s2.0-1', '2-s2.0-2']);
  });
});
