import { AdditionalIdentifier, Registration } from '../../../types/registration.types';

const prioritiseIdentifiersFromCristin = (a: AdditionalIdentifier, b: AdditionalIdentifier): number => {
  if (a.sourceName === 'Cristin') {
    return -1;
  }
  if (b.sourceName === 'Cristin') {
    return 1;
  }
  return 0;
};

const minNvaSyntheticCristinIdentifier = 10_000_000;

/**
 * Handles issued by the Norwegian institutional archives (Brage) share the prefix 11250, as in
 * https://hdl.handle.net/11250/3001. Matching the whole path segment avoids also matching handles
 * where 11250 merely happens to start the suffix, such as https://hdl.handle.net/10852/112507.
 */
const institutionalArchiveHandlePattern = /(^|\/)11250\//;

/**
 * Collects every handle on a registration, deduplicated. A handle can live either on
 * registration.handle or in additionalIdentifiers. registration.handle is always listed first.
 */
export const getHandles = (registration: Registration): string[] => {
  const additionalHandles =
    registration.additionalIdentifiers
      ?.filter((identifier) => identifier.type === 'HandleIdentifier' || identifier.sourceName === 'handle')
      .map((identifier) => identifier.value) ?? [];

  return [...new Set([registration.handle, ...additionalHandles])].filter((handle): handle is string => !!handle);
};

/**
 * Splits handles into the one shown by default and the rest, which are hidden behind a toggle.
 * Prefers the first handle from an institutional archive, otherwise falls back to the first handle.
 */
export const splitHandles = (handles: string[]): { primaryHandles: string[]; otherHandles: string[] } => {
  if (handles.length === 0) {
    return { primaryHandles: [], otherHandles: [] };
  }

  const archiveHandleIndex = handles.findIndex((handle) => institutionalArchiveHandlePattern.test(handle));
  const primaryIndex = archiveHandleIndex === -1 ? 0 : archiveHandleIndex;

  return {
    primaryHandles: [handles[primaryIndex]],
    otherHandles: handles.filter((_, index) => index !== primaryIndex),
  };
};

/** Returns the Cristin identifier to display, ignoring the synthetic ones NVA generates itself. */
export const getCristinIdentifier = (registration: Registration): string | undefined =>
  registration.additionalIdentifiers
    ?.filter(
      (identifier) =>
        (identifier.type === 'CristinIdentifier' || identifier.sourceName === 'Cristin') &&
        +identifier.value < minNvaSyntheticCristinIdentifier // Omit IDs generated by NVA
    )
    .sort((a, b) => prioritiseIdentifiersFromCristin(a, b))
    .shift()?.value;

export const getScopusIdentifiers = (registration: Registration): string[] =>
  registration.additionalIdentifiers
    ?.filter((identifier) => identifier.type === 'ScopusIdentifier' || identifier.sourceName === 'Scopus')
    .map((identifier) => identifier.value) ?? [];
