import { AdditionalIdentifier, Registration } from '../../../types/registration.types';

const prioritiseIdentifiersFromCristin = (a: AdditionalIdentifier, b: AdditionalIdentifier): number => {
  if (a.sourceName === 'Cristin') {
    return -1;
  }
  if (b.sourceName === 'Cristin') {
    return 1;
  }
  return 0;
};

const minNvaSyntheticCristinIdentifier = 10_000_000;

// 11250 is the handle prefix for Brage, the institutional archive. Its handles point to the archived full text.
const institutionalArchiveHandlePattern = /(^|\/)11250\//;

/**
 * Collects every handle on a registration, deduplicated. A handle can live either on
 * registration.handle or in additionalIdentifiers. registration.handle is always listed first.
 */
export const getHandles = (registration: Registration): string[] => {
  const additionalHandles =
    registration.additionalIdentifiers
      ?.filter((identifier) => identifier.type === 'HandleIdentifier' || identifier.sourceName === 'handle')
      .map((identifier) => identifier.value) ?? [];

  return [...new Set([registration.handle, ...additionalHandles])].filter((handle): handle is string => !!handle);
};

/**
 * Splits handles into the one shown by default and the rest, which are hidden behind a toggle.
 * Shows the first institutional archive (Brage) handle if there is one, otherwise the first handle in the list.
 */
export const splitHandles = (handles: string[]): { primaryHandle?: string; otherHandles: string[] } => {
  if (handles.length === 0) {
    return { otherHandles: [] };
  }

  const archiveHandleIndex = handles.findIndex((handle) => institutionalArchiveHandlePattern.test(handle));
  const primaryIndex = archiveHandleIndex === -1 ? 0 : archiveHandleIndex;

  return {
    primaryHandle: handles[primaryIndex],
    otherHandles: handles.filter((_, index) => index !== primaryIndex),
  };
};

/** Returns the Cristin identifier to display, ignoring the synthetic ones NVA generates itself. */
export const getCristinIdentifier = (registration: Registration): string | undefined =>
  registration.additionalIdentifiers
    ?.filter(
      (identifier) =>
        (identifier.type === 'CristinIdentifier' || identifier.sourceName === 'Cristin') &&
        +identifier.value < minNvaSyntheticCristinIdentifier // Omit IDs generated by NVA
    )
    .sort((a, b) => prioritiseIdentifiersFromCristin(a, b))
    .shift()?.value;

export const getScopusIdentifiers = (registration: Registration): string[] =>
  registration.additionalIdentifiers
    ?.filter((identifier) => identifier.type === 'ScopusIdentifier' || identifier.sourceName === 'Scopus')
    .map((identifier) => identifier.value) ?? [];
