export const dataTestId = {
  basicData: {
    addEmployeeLink: 'add-employee-link',
    adminInstitutionsLink: 'admin-institutions-link',
    adminUsersLink: 'admin-users-link',
    centralImportLink: 'central-import-link',
    centralImport: {
      checkboxAuthor: 'duplicate-search-author-checkbox',
      checkboxDoi: 'duplicate-search-doi-checkbox',
      checkboxIssn: 'duplicate-search-issn-checkbox',
      checkboxTitle: 'duplicate-search-title-checkbox',
      checkboxYear: 'duplicate-search-year-checkbox',
      searchPagination: 'search-pagination',
      resetButton: 'duplicate-search-reset-button',
      resultItem: 'central-import-result-item',
      searchButton: 'duplicate-search-retry-button',
      textFieldAuthor: 'duplicate-search-author-textfield',
      textFieldDoi: 'duplicate-search-doi-textfield',
      textFieldIssn: 'duplicate-search-issn-textfield',
      textFieldTitle: 'duplicate-search-title-textfield',
      textFieldYear: 'duplicate-search-year-textfield',
    },
    customers: {
      addCustomerButton: 'add-institution-button',
      customerList: 'customer-institutions-list',
      editInstitutionButton: (name: string) => `edit-institution-button-${name.toLowerCase().replaceAll(' ', '-')}`,
    },
    personRegisterLink: 'person-register-link',
  },
  confirmDialog: {
    acceptButton: 'accept-button',
    cancelButton: 'cancel-button',
  },
  organization: {
    searchField: 'organization-search-field',
    subSearchField: 'sub-organization-search-field',
  },
  editor: {
    hrcsActivityButtonGroup: 'hrcs-activity-button-group',
    hrcsCategoryButtonGroup: 'hrcs-category-button-group',
  },
  header: {
    aboutLink: 'about-link',
    basicDataLink: 'basic-data-link',
    editorLink: 'editor-link',
    generalMenuButton: 'general-menu-button',
    languageButton: 'language-button',
    languageMenu: 'language-menu',
    logInButton: 'log-in-link',
    logOutLink: 'log-out-link',
    menuButton: 'menu-button',
    myPageLink: 'my-page-link',
    newRegistrationLink: 'new-registration',
    privacyLink: 'privacy-link',
    worklistLink: 'worklist-link',
  },
  institutionAdmin: {
    archiveNameField: 'archive-field',
    displayNameField: 'display-name-field',
    feideField: 'feide-field',
    nameField: 'institution-name-field',
    rorField: 'ror-field',
    saveButton: 'save-button',
    shortNameField: 'short-name-field',
  },
  startPage: {
    orderBySelect: 'order-by-select',
    readMoreButton: 'button-read-more',
    searchButton: 'search-button',
    searchField: 'search-field',
    searchPagination: 'search-pagination',
    searchResultItem: 'result-list-item',
  },
  projectLandingPage: {
    generalInfoBox: 'general-info',
    participantsAccordion: 'participants-accordion',
    resultsAccordion: 'results-accordion',
    scientificSummaryAccordion: 'scientific-summary-accordion',
  },
  registrationLandingPage: {
    abstractAccordion: 'abstract-accordion',
    authorLink: (id: string) => `presentation-author-link-${id}`,
    backToWizard: 'back-to-wizard-button',
    contributors: 'public-registration-contributors',
    createDoiButton: 'button-create-doi',
    dmpAccordion: 'dmp-accordion',
    doiLink: 'doi-link',
    doiMessageField: 'request-doi-message',
    doiOriginalLink: 'doi-original-link',
    editButton: 'button-edit-registration',
    emailButton: 'email-button',
    externalLinksAccordion: 'external-links-accordion',
    facebookButton: 'facebook-button',
    file: 'file',
    fileEmbargoDate: 'file-embargo-date',
    fileName: 'file-name',
    filePreview: 'file-preview',
    filePreviewHeader: 'file-preview-header',
    fileSize: 'file-size',
    fileVersion: 'file-version',
    filesAccordion: 'files-accordion',
    generalInfo: 'public-registration-general-info',
    geographicAccordion: 'geographic-accordion',
    keywords: 'public-registration-keywords',
    license: 'public-registration-license',
    linkedInButton: 'linkedin-button',
    npi: 'public-registration-npi',
    openFileButton: 'open-file-button',
    primaryLanguage: 'public-registration-primary-language',
    projectsAccordion: 'projects-accordion',
    projectTitle: 'project-title',
    publicationDate: 'public-registration-publication-date',
    publicationsUsingDatasetAccordion: 'publications-using-dataset-accordion',
    publishButton: 'button-publish-registration',
    publishingRequestAcceptButton: 'publishing-request-accept-button',
    publishingRequestRejectButton: 'publishing-request-reject-button',
    registrationSubtype: 'public-registration-registration-subtype',
    rejectDoiButton: 'button-reject-doi',
    relatedPublicationsAccordion: 'related-publications-accordion',
    relatedRegistrationsAccordion: 'related-registrations-accordion',
    requestDoiButton: 'button-toggle-request-doi',
    reserveDoiButton: 'button-toggle-reserve-doi',
    requestDoiModal: 'request-doi-modal',
    sendDoiButton: 'button-send-doi-request',
    status: 'public-registration-status',
    subtypeFields: 'public-registration-subtype-fields',
    title: 'public-registration-title',
    twitterButton: 'twitter-button',
  },
  registrationWizard: {
    contributors: {
      addAffiliationButton: 'button-add-affiliation',
      addContributorButton: (role: string) => `add-${role}`,
      addSelfButton: 'add-self-button',
      addUnverifiedContributorButton: 'add-unverified-contributor-button',
      authorRadioButton: 'author-radio-button',
      correspondingCheckbox: 'author-corresponding-checkbox',
      verifyAffiliationButton: 'button-set-unverified-affiliation',
      verifyContributorButton: (name: string) => `button-set-unverified-contributor-${name}`,
      removeAffiliationButton: 'button-remove-affiliation',
      removeContributorButton: (name: string) => `button-remove-contributor-${name}`,
      searchField: 'search-field',
      selectContributorType: 'select-contributor-type',
      selectUserButton: 'select-user-button',
      unverifiedContributorName: 'unverified-contributor-name',
    },
    description: {
      addVocabularyButton: 'add-vocabulary-button',
      datePublishedField: 'date-published-field',
      projectForm: {
        contributorsSearchField: 'project-contributors-search-field',
        endDateField: 'project-end-date-field',
        roleField: 'project-participant-role-field',
        startDateField: 'project-start-date-field',
        titleField: 'project-title-field',
      },
      projectSearchField: 'project-search-field',
      abstractField: 'registration-abstract-field',
      descriptionField: 'registration-description-field',
      languageField: 'registration-language-field',
      tagField: 'registration-tag-field',
      titleField: 'registration-title-field',
      vocabularyMenuItem: (vocabulary: string) => `vocabulary-menu-item-${vocabulary}`,
      vocabularyRow: (vocabulary: string) => `vocabulary-row-${vocabulary}`,
    },
    files: {
      administrativeAgreement: 'administrative-agreement-checkbox',
      embargoDateField: 'embargo-date-field',
      fileCard: 'uploaded-file-card',
      licenseHelpButton: 'license-help-button',
      licenseItem: 'license-item',
      licenseModal: 'license-modal',
      removeFileButton: 'button-remove-file',
      selectLicenseField: 'uploaded-file-select-license',
      version: 'version-radios',
    },
    new: {
      emptyRegistrationAccordion: 'new-registration-empty',
      fileAccordion: 'new-registration-file',
      linkAccordion: 'new-registration-link',
      linkMetadata: 'link-metadata',
      startRegistrationButton: 'registration-start-button',
    },
    resourceType: {
      addAudioVideoButton: 'add-audio-video-button',
      addCompetitionButton: 'add-competition-button',
      addExhibitionButton: 'add-exhibition-button',
      addMentionInPublicationButton: 'add-mention-in-publication-button',
      addAwardButton: 'add-award-button',
      addVenueButton: 'add-venue-button',
      addTvWebStreamingButton: 'add-tv-web-streaming-button',
      addFestivalCinemaButton: 'add-festival-cinema-button',
      addOtherButton: 'add-other-button',
      addPerformanceButton: 'add-performance-button',
      addBookButton: 'add-book-button',
      addConcertShowButton: 'add-concert-show-button',
      addAudioVideoPublicationButton: 'add-audio-video-publication-button',
      addScoreManuscriptButton: 'add-score-manuscript-button',
      addWebPublicationButton: 'add-web-publication-button',
      articleNumberField: 'article-number-field',
      artisticTypeField: 'artistic-type-field',
      artisticDescriptionField: 'artistic-description-field',
      artisticOtherTypeField: 'artistic-other-type-field',
      artisticOutputDate: 'artistic-output-date',
      artisticOutputDuration: 'artistic-output-duration',
      artisticOutputSaveButton: 'artistic-output-save-button',
      artisticSubtype: 'artistic-subtype',
      audioVideoAddTrack: 'audio-video-add-track',
      audioVideoPublisher: 'audio-video-publisher',
      audioVideoCatalogueNumber: 'audio-video-catalogue-number',
      audioVideoContentTitle: 'audio-video-content-title',
      audioVideoContentComposer: 'audio-video-content-composer',
      audioVideoContentRemove: 'audio-video-content-remove',
      awardName: 'artistic-award-name',
      awardOrganizer: 'artistic-award-organizer',
      awardOther: 'artistic-award-other',
      awardRanking: 'artistic-award-ranking',
      broadcastPublisher: 'artistic-broadcast-publisher',
      cinemaPlace: 'artistic-cinema-place',
      competitionDescription: 'artistic-competition-description',
      competitionName: 'artistic-competition-name',
      compliesWithField: 'complies-with-field',
      concertAddWork: 'concert-add-work',
      concertPartOfSeries: 'concert-part-of-series',
      concertPlace: 'concert-place',
      concertProgramTitle: 'concert-program-title',
      concertProgramComposer: 'concert-program-composer',
      concertProgramIsPremiere: 'concert-program-is-premiere',
      concertProgramRemove: 'concert-program-remove',
      contentField: 'content-field',
      contentValue: (value: string) => `content-value-${value.toLowerCase()}`,
      corrigendumForField: 'corrigendum-for-field',
      eventCountryField: 'event-country-field',
      exhibitionName: 'artistic-exhibition-name',
      exhibitionPlace: 'artistic-exhibition-place',
      exhibitionOrganizer: 'artistic-exhibition-organizer',
      exhibitionOther: 'artistic-exhibition-other',
      externalLinkField: 'external-link-field',
      externalLinkAddButton: 'external-link-add-button',
      externalLink: 'external-link',
      geographicDescriptionField: 'geographic-description-field',
      dateFromField: 'date-from-field',
      dateToField: 'date-to-field',
      eventOrganizerField: 'event-organizer-field',
      eventTitleField: 'event-title-field',
      isbnField: 'isbn-field',
      issueField: 'issue-field',
      journalChip: 'journal-chip',
      journalField: 'journal-search-field',
      linkField: 'link-field',
      nviFailed: 'not-nvi-applicable',
      nviSuccess: 'nvi-applicable',
      otherReleaseType: 'artistic-other-release-type',
      otherReleasePlace: 'artistic-other-release-place',
      otherReleasePublisher: 'artistic-other-release-publisher',
      otherPerfomanceAddWork: 'music-other-performance-add-work',
      otherPerformancePlace: 'music-other-performance-place',
      otherPerformanceType: 'music-other-performance-type',
      otherPerformanceWorkTitle: 'music-other-work-title',
      otherPerformanceWorkComposer: 'music-other-work-composer',
      otherPerformanceWorkRemove: 'music-other-work-remove',
      pagesField: 'pages-field',
      pagesFromField: 'pages-from-field',
      pagesToField: 'pages-to-field',
      partOfField: 'part-of-field',
      placeField: 'place-field',
      publicationMentionTitle: 'artistic-publication-mention-title',
      publicationMentionIssue: 'artistic-publication-mention-issue',
      publicationMentionOther: 'artistic-publication-mention-other',
      publisherChip: 'publisher-chip',
      publisherField: 'publisher-search-field',
      publisherNameField: 'publisher-name-field',
      relatedRegistrationField: 'related-registration-field',
      relatedRegistrationLink: (value: string) => `related-registration-link-${value}`,
      removePublisherButton: 'remove-publisher-button',
      removeRelationButton: (value: string) => (value ? `remove-relation-button-${value}` : 'remove-relation-button'),
      scientificSubjectField: 'scientific-subject-field',
      scoreEnsemble: 'score-ensemble',
      scoreMovements: 'score-movements',
      scorePublisher: 'score-publisher',
      scoreIsmn: 'score-ismn',
      scoreIsrc: 'score-isrc',
      seriesChip: 'series-chip',
      seriesField: 'series-search-field',
      seriesNumber: 'series-number-field',
      venueNameField: 'venue-name-field',
      volumeField: 'volume-field',
    },
    stepper: {
      contributorsStepButton: 'nav-tabpanel-contributors',
      descriptionStepButton: 'nav-tabpanel-description',
      errorStep: 'error-tab',
      filesStepButton: 'nav-tabpanel-files-and-license',
      resourceStepButton: 'nav-tabpanel-resource-type',
    },
  },
  myInstitutionUsersPage: {
    areaOfResponsibilityField: 'area-of-responsibility-field',
    usersAdministrators: 'users-administrators',
    usersCurators: 'users-curators',
    usersEditors: 'users-editors',
    usersCreators: 'users-creators',
  },
  myPage: {
    messagesLink: 'messages-link',
    myProfileLink: 'my-profile-link',
    myRegistrationsLink: 'my-registrations-link',
    newRegistrationLink: 'new-registration-link',
    researchProfileLink: 'research-profile-link',
  },
};
