export const dataTestId = {
  footer: {
    aboutLink: 'about-link',
    privacyLink: 'privacy-link',
  },
  header: {
    adminUsersLink: 'admin-users-link',
    adminInstitutionLink: 'admin-institutions-link',
    adminInstitutionsLink: 'admin-institutions-link',
    languageButton: 'language-button',
    languageMenu: 'language-menu',
    logInButton: 'log-in-link',
    logOutLink: 'log-out-link',
    menuButton: 'menu-button',
    myProfileLink: 'my-profile-link',
    worklistLink: 'worklist-link',
  },
  startPage: {
    readMoreButton: 'button-read-more',
    searchButton: 'search-button',
    searchField: 'search-field',
    searchPagination: 'search-pagination',
  },
  projectLandingPage: {
    generalInfoBox: 'general-info',
    participantsAccordion: 'participants-accordion',
    resultsAccordion: 'results-accordion',
    scientificSummaryAccordion: 'scientific-summary-accordion',
  },
  registrationLandingPage: {
    abstractAccordion: 'abstract-accordion',
    authorLink: (id: string) => `presentation-author-link-${id}`,
    backToWizard: 'back-to-wizard-button',
    contributors: 'public-registration-contributors',
    createDoiButton: 'button-create-doi',
    doiLink: 'public-registration-doi-link',
    doiMessageField: 'request-doi-message',
    downloadFileButton: 'button-download-file',
    editButton: 'button-edit-registration',
    filesAccordion: 'files-accordion',
    keywords: 'public-registration-keywords',
    license: 'public-registration-license',
    npi: 'public-registration-npi',
    primaryLanguage: 'public-registration-primary-language',
    projectsAccordion: 'projects-accordion',
    projectTitle: 'project-title',
    publicationDate: 'public-registration-publication-date',
    publishButton: 'button-publish-registration',
    registrationSubtype: 'public-registration-registration-subtype',
    rejectDoiButton: 'button-reject-doi',
    relatedRegistrationsAccordion: 'related-registrations-accordion',
    requestDoiButton: 'button-toggle-request-doi',
    requestDoiModal: 'request-doi-modal',
    sendDoiButton: 'button-send-doi-request',
    status: 'public-registration-status',
    subtypeFields: 'public-registration-subtype-fields',
    title: 'public-registration-title',
  },
  registrationWizard: {
    description: {
      addVocabularyButton: 'add-vocabulary-button',
      vocabularyMenuItem: (vocabulary: string) => `vocabulary-menu-item-${vocabulary}`,
      vocabularyRow: (vocabulary: string) => `vocabulary-row-${vocabulary}`,
    },
    files: {
      administrativeAgreement: 'administrative-agreement-checkbox',
      version: 'version-radios',
    },
    resourceType: {
      contentField: 'content-field',
      contentValue: (value: string) => `content-value-${value.toLowerCase().replaceAll(' ', '-')}`,
      isbnField: 'isbn-field',
      journalField: 'journal-search-field',
      nviFailedPeerReview: 'nvi-failed-not-peer-reviewed',
      nviFailedRated: 'nvi-failed-not-rated',
      nviSuccess: 'nvi-applicable',
      pagesField: 'pages-field',
      pagesFromField: 'pages-from-field',
      pagesToField: 'pages-to-field',
      peerReviewed: 'peer-review-field',
      publisherField: 'publisher-search-field',
      removePublisherButton: 'remove-publisher-button',
      removeJournalButton: 'remove-journal-button',
      removeSeriesButton: 'remove-series-button',
      seriesField: 'series-search-field',
      seriesNumber: 'series-number-field',
    },
  },
  myInstitutionUsersPage: {
    usersAdministrators: 'users-administrators',
    usersCurators: 'users-curators',
    usersEditors: 'users-editors',
    usersCreators: 'users-creators',
  },
};
