AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates a pipeline for building and deploying a web application to a CloudFront distribution

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NVA-Frontend
    Description: Frontend for NVA
    Author: Unit
    SemanticVersion: 1.0.0
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE

Parameters:
  GitHubOAuthToken:
    Description: OAuth token used by AWS CodePipeline to connect to GitHub
    NoEcho: true
    Type: String
  GitHubOwner:
    Description: GitHub username owning the repo
    Type: String
    Default: BIBSYSDEV
  GitHubRepo:
    Description: GitHub repo name
    Type: String
    Default: NVA-Frontend
  GitHubBranch:
    Description: GitHub repo branch name. It defaults to master if not specified.
    Type: String
    Default: master
  UseMockData:
    Description: Set true to use mock data for testing purposes
    Type: String
    Default: false
  FrontendTemplateBucket:
    Description: Common bucket for frontend templates
    Type: String
  FrontendDomainCertificateArn:
    Description: Certificate to use for frontend
    Type: String

Resources:
  FrontendBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${FrontendTemplateBucket}.s3-eu-west-1.amazonaws.com/s3_template.yml'
      TimeoutInMinutes: 60
  CloudfrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${FrontendTemplateBucket}.s3-eu-west-1.amazonaws.com/cloudfront_template.yml'
      TimeoutInMinutes: 60
      Parameters:
        NvaFrontendBucketName: !GetAtt FrontendBucketStack.Outputs.BucketName
        DomainCertificateArn: !Ref FrontendDomainCertificateArn
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${FrontendTemplateBucket}.s3-eu-west-1.amazonaws.com/pipeline_template.yml'
      TimeoutInMinutes: 60
      Parameters:
        GitHubOAuthToken: !Ref GitHubOAuthToken
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        FrontendBucketName: !GetAtt FrontendBucketStack.Outputs.BucketName
        UseMockData: !Ref UseMockData
        CloudfrontDistribution: !GetAtt CloudfrontStack.Outputs.CloudFrontDistribution
