// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id: 'eu-west-1:4ad26e8d-9549-4cda-82e5-29bc4e3939d4',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_uhKzlCZfT',
  aws_user_pools_web_client_id: '78b6opjourcak7gvr1c9r8u5re', //svenn-nva2
  //aws_user_pools_web_client_id: '59fug4072l4qevqhrguois8dn7',// svenn-nva
  oauth: {
    domain: 'svenn-nva.auth.eu-west-1.amazoncognito.com',
    scope: ['openid'],
    redirectSignIn: 'http://localhost:3000/',
    redirectSignOut: 'http://localhost:3000/',
    responseType: 'code',
  },
};

export default awsmobile;
