// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id: 'eu-west-1:6afdf2ee-af71-459e-97ca-6073adfc9a29',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_E7gc1PzR2',
  aws_user_pools_web_client_id: 'jlkel8sdu61v19ughlm7sc0la',
  oauth: {
    domain: 'nva-test-user-pool.auth.eu-west-1.amazoncognito.com',
    scope: ['openid'],
    redirectSignIn: 'http://localhost:3000/',
    redirectSignOut: 'http://localhost:3000/',
    responseType: 'code',
  },
};

export default awsmobile;
