import { Journal } from '../../types/registration.types';

export const mockJournalsSearch: Journal[] = [
  {
    id: 'https://api.dev.nva.aws.unit.no/publication-channels/journal/1/2020',
    identifier: '1',
    name: 'Journal number 1',
    website: 'http://www.journal4.com/',
    level: '1',
    active: true,
    onlineIssn: '1111-1111',
    printIssn: '1111-1112',
    npiDomain: 'Biologi',
    openAccess: null,
    language: null,
    publisherId: null,
  },
  {
    id: 'https://api.dev.nva.aws.unit.no/publication-channels/journal/2/2020',
    identifier: '2',
    name: 'Journal number 2',
    website: 'http://www.journal2.com/',
    level: '1',
    active: true,
    onlineIssn: '2222-2222',
    printIssn: null,
    npiDomain: 'Kunsthistorie',
    openAccess: null,
    language: 'Engelsk',
    publisherId: null,
  },
  {
    id: 'https://api.dev.nva.aws.unit.no/publication-channels/journal/3/2020',
    identifier: '3',
    name: 'Journal number 3',
    website: 'http://www.journal3.com/',
    level: '1',
    active: true,
    onlineIssn: '3333-3333',
    printIssn: '3333-3334',
    npiDomain: 'Sosialantropologi',
    openAccess: null,
    language: 'Engelsk',
    publisherId: 'https://api.dev.nva.aws.unit.no/publication-channels/publisher/1/2020',
  },
];
