import { CustomerInstitution, CustomerList } from '../../types/customerInstitution.types';

export const mockCustomerInstitution: CustomerInstitution = {
  type: '',
  id: 'https://api.dev.nva.aws.unit.no/customer/1',
  name: 'Norwegian University of Science and Technology',
  identifier: '1',
  createdDate: '2020-11-01',
  displayName: 'Norwegian University of Science and Technology',
  shortName: 'NTNU',
  archiveName: 'NTNU Open',
  cname: 'ntnu.unit.nva.no',
  cristinId: 'https://api.cristin.no/v2/institutions/194',
  institutionDns: '1.1.1.1',
  feideOrganizationId: 'NO919477822',
};

export const mockCustomerInstitutions: CustomerList = {
  customers: [
    mockCustomerInstitution,
    {
      id: 'https://api.dev.nva.aws.unit.no/customer/2',
      name: 'Statped',
      identifier: '2',
      createdDate: '2020-11-01',
      displayName: 'xxx',
      shortName: 'xxx',
      archiveName: 'xxx',
      cname: 'xxx',
      cristinId: 'https://api.cristin.no/v2/institutions/2',
      institutionDns: 'xxx',
      feideOrganizationId: 'xxx',
    },
    {
      id: 'https://api.dev.nva.aws.unit.no/customer/3',
      name: 'Anno Museeum',
      identifier: '3',
      createdDate: '2020-11-01',
      displayName: 'xxx',
      shortName: 'xxx',
      archiveName: 'xxx',
      cname: 'xxx',
      cristinId: 'https://api.cristin.no/v2/institutions/3',
      institutionDns: 'xxx',
      feideOrganizationId: 'xxx',
    },
    {
      id: 'https://api.dev.nva.aws.unit.no/customer/4',
      name: 'Institutt for osteloff',
      identifier: '4',
      createdDate: '2020-01-27',
      displayName: 'xxx',
      shortName: 'xxx',
      archiveName: 'xxx',
      cname: 'xxx',
      cristinId: 'https://api.cristin.no/v2/institutions/4',
      institutionDns: 'xxx',
      feideOrganizationId: 'xxx',
    },
    {
      id: 'https://api.dev.nva.aws.unit.no/customer/5',
      name: 'Norsk senter for økologisk landbruk',
      identifier: '5',
      createdDate: '2012-11-11',
      displayName: 'xxx',
      shortName: 'xxx',
      archiveName: 'xxx',
      cname: 'xxx',
      cristinId: 'https://api.cristin.no/v2/institutions/5',
      institutionDns: 'xxx',
      feideOrganizationId: 'xxx',
    },
  ],
};
