import {
  CustomerInstitution,
  CustomerList,
  VocabularyList,
  VocabularyStatus,
} from '../../types/customerInstitution.types';

export const mockCustomerInstitutionVocabularies: VocabularyList = {
  type: 'VocabularyList',
  id: 'https://api.dev.nva.aws.unit.no/customer/f54c8aa9-073a-46a1-8f7c-dde66c853934/vocabularies',
  vocabularies: [
    {
      type: 'Vocabulary',
      name: 'HRCS Category',
      id: 'https://nva.unit.no/hrcs/category',
      status: VocabularyStatus.Allowed,
    },
    {
      type: 'Vocabulary',
      name: 'HRCS Activity',
      id: 'https://nva.unit.no/hrcs/activity',
      status: VocabularyStatus.Default,
    },
  ],
};

export const mockCustomerInstitution: CustomerInstitution = {
  id: 'https://api.dev.nva.aws.unit.no/customer/1',
  name: 'Norwegian University of Science and Technology',
  identifier: '1',
  createdDate: '2020-11-01',
  displayName: 'Norwegian University of Science and Technology',
  shortName: 'NTNU',
  archiveName: 'NTNU Open',
  cname: 'ntnu.unit.nva.no',
  cristinId: 'https://api.cristin.no/v2/institutions/194',
  institutionDns: '1.1.1.1',
  feideOrganizationId: 'NO919477822',
  vocabularies: mockCustomerInstitutionVocabularies.vocabularies,
};

export const mockCustomerInstitutions: CustomerList = {
  customers: [
    mockCustomerInstitution,
    {
      id: 'https://api.dev.nva.aws.unit.no/customer/2',
      name: 'Statped',
      identifier: '2',
      createdDate: '2020-11-01',
      displayName: 'xxx',
      shortName: 'xxx',
      archiveName: 'xxx',
      cname: 'xxx',
      cristinId: 'https://api.cristin.no/v2/institutions/2',
      institutionDns: 'xxx',
      feideOrganizationId: 'xxx',
      vocabularies: [],
    },
    {
      id: 'https://api.dev.nva.aws.unit.no/customer/3',
      name: 'Anno Museeum',
      identifier: '3',
      createdDate: '2020-11-01',
      displayName: 'xxx',
      shortName: 'xxx',
      archiveName: 'xxx',
      cname: 'xxx',
      cristinId: 'https://api.cristin.no/v2/institutions/3',
      institutionDns: 'xxx',
      feideOrganizationId: 'xxx',
      vocabularies: [],
    },
    {
      id: 'https://api.dev.nva.aws.unit.no/customer/4',
      name: 'Institutt for osteloff',
      identifier: '4',
      createdDate: '2020-01-27',
      displayName: 'xxx',
      shortName: 'xxx',
      archiveName: 'xxx',
      cname: 'xxx',
      cristinId: 'https://api.cristin.no/v2/institutions/4',
      institutionDns: 'xxx',
      feideOrganizationId: 'xxx',
      vocabularies: [],
    },
    {
      id: 'https://api.dev.nva.aws.unit.no/customer/5',
      name: 'Norsk senter for økologisk landbruk',
      identifier: '5',
      createdDate: '2012-11-11',
      displayName: 'xxx',
      shortName: 'xxx',
      archiveName: 'xxx',
      cname: 'xxx',
      cristinId: 'https://api.cristin.no/v2/institutions/5',
      institutionDns: 'xxx',
      feideOrganizationId: 'xxx',
      vocabularies: [],
    },
  ],
};
